name: Check Github Tags

on: push

jobs: 
  check-git-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print Repository info
          run: |
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
            echo $GITHUB_REF
            git tag
      - name: Push new tag
        if: failure()
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ers-test2
      - name: Get All Repo Tags
        run: |
          git tag