name: Check Github Tags

on: push

jobs: 
  check-git-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print Repository info
        run: |
          echo 'Commit:' $GITHUB_SHA
          echo 'Repository:' $GITHUB_REPOSITORY
          echo 'Workspace:' $GITHUB_WORKSPACE
          echo 'Ref:' $GITHUB_REF
          git tag
      - name: Push new tag
        id: push_new_tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ers-test2
      - name: Print New Tag Added
        run: echo 'New tag ' ${{steps.push_new_tag.outputs.new_tag}} 'added to ' $GITHUB_REPOSITORY. 