name: Check Github Tags

on: push

jobs: 
  check-git-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print Repository info
        run: |
          print('Commit:' $GITHUB_SHA)
          print('Repository:' $GITHUB_REPOSITORY)
          print('Workspace:' $GITHUB_WORKSPACE)
          print('Ref:' $GITHUB_REF)
          git tag
      - name: Push new tag
        if: 
        id: push_new_tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: test2
      - name: Print New Tag Added
        if: success()
        run: print('New tag' ${{steps.push_new_tag.outputs.new_tag}} 'added to commit' $GITHUB_SHA 'in' $GITHUB_REPOSITORY).